spring:
  data:
    mongodb:
      uri: mongodb+srv://alirizwan05681_db_user:u34dQPkbPn4AOqMyl@cluster0.68aofs7.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true





    redis:
#      uri:
      host: redis-18789.crce263.ap-south-1-1.ec2.cloud.redislabs.com
      port: 18789
      password: QNrSQlStP8GrmXqpJGH80bUJw7xFErtz

#      "::1"
#      6379
#      database: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: rizz84211@gmail.com
    password: aixj qmbv aqua wtbi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true


server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: "cb229c840d4f7703c0f82652d4402de2"
#spring:
#  profiles:
#    active: dev
#
#logging:
#  level:
#    net:
#      engineeringdigest:
#        journalApp: DEBUG
